# Generated by Django 6.0.6 on 2026-07-21 20:59

import core.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientprofile_is_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='Trading Account', max_length=100)),
                ('account_code', models.CharField(default=core.models.make_account_code, max_length=30, unique=True)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('repayment_period_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to='core.clientprofile')),
            ],
        ),
    ]
